FROM clickhouse/clickhouse-server:24.8.7.41

COPY posthog/idl /idl
COPY docker/clickhouse/docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
COPY docker/clickhouse/config.xml /etc/clickhouse-server/config.xml
COPY docker/clickhouse/config.d/default.xml /etc/clickhouse-server/config.d/default.xml
COPY docker/clickhouse/users.xml /etc/clickhouse-server/users.xml
COPY docker/clickhouse/user_defined_function.xml /etc/clickhouse-server/user_defined_function.xml
COPY posthog/user_scripts /var/lib/clickhouse/user_scripts
